apiVersion: 1

deleteDatasources:
  - name: POSTGRES_ORG_VALUES
    orgId: 1

datasources:
- name: POSTGRES_ORG_VALUES 
  type: postgres 
  access: proxy
  url: db 
  user: updateUser
  database: dbUpdate 
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
    sslmode: 'disable' # disable/require/verify-ca/verify-full
    timescaledb: false
  secureJsonData:
    password: "secret"
  version: 1
  editable: true